<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KompetensiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('kompetensi')->insert([
            ['id_kompetensi'=>1,'kode_kompetensi'=>'R1','kompetensi'=>'Mengidentifikasi Peraturan Perundang-undangan Terkait Pelindungan Data Pribadi'],
            ['id_kompetensi'=>2,'kode_kompetensi'=>'R2','kompetensi'=>'Menyusun Kriteria Matriks Risiko Pelindungan Data Pribadi'],
            ['id_kompetensi'=>3,'kode_kompetensi'=>'R3','kompetensi'=>'Melakukan Penilaian Dampak Pelindungan Data Pribadi'],
            ['id_kompetensi'=>4,'kode_kompetensi'=>'R4','kompetensi'=>'Mensupervisi Kelayakan Pelaksanaan Prosedur Audit Teknologi Informasi'],
            ['id_kompetensi'=>5,'kode_kompetensi'=>'R5','kompetensi'=>'Menganalisis Risiko Audit Teknologi Informasi & Menyusun Rencana Audit Teknologi Informasi'],
            ['id_kompetensi'=>6,'kode_kompetensi'=>'R6','kompetensi'=>'Menilai Hasil Pelaksanaan Prosedur Audit atas Kontrol Teknologi Informasi'],
            ['id_kompetensi'=>7,'kode_kompetensi'=>'R7','kompetensi'=>'Menyusun Hasil Audit Teknologi Informasi & Menyusun Rekomendasi Audit Teknologi Informasi'],
            ['id_kompetensi'=>8,'kode_kompetensi'=>'R8','kompetensi'=>'Memverifikasi Kelayakan Tindak Lanjut Audit Teknologi Informasi'],
            ['id_kompetensi'=>9,'kode_kompetensi'=>'R9','kompetensi'=>'Prepare a Project Brief & Prepare Project Specifications'],
            ['id_kompetensi'=>10,'kode_kompetensi'=>'R10','kompetensi'=>'Prepare & Coordinate for The Build Phase of an ICT System'],
            ['id_kompetensi'=>11,'kode_kompetensi'=>'R11','kompetensi'=>'Develop Integration Blueprint for ICT Systems'],
            ['id_kompetensi'=>12,'kode_kompetensi'=>'R12','kompetensi'=>'Melakukan Instalasi Application Server dan Database Sistem ERP'],
            ['id_kompetensi'=>13,'kode_kompetensi'=>'R13','kompetensi'=>'Menentukan Teknologi Cloud Computing'],
            ['id_kompetensi'=>14,'kode_kompetensi'=>'R14','kompetensi'=>'Merekayasa Arsitektur Virtualisasi Sistem Public/Private/Hybrid/Sovereign Cloud'],
            ['id_kompetensi'=>15,'kode_kompetensi'=>'R15','kompetensi'=>'Menentukan Metode Pemodelan Arsitektur Bisnis dan Business Building Block yang Diperlukan'],
            ['id_kompetensi'=>16,'kode_kompetensi'=>'R16','kompetensi'=>'Menyusun Roadmap Arsitektur Bisnis dan Komponen Arsitektur Data'],
            ['id_kompetensi'=>17,'kode_kompetensi'=>'R17','kompetensi'=>'Mengevaluasi Artefak Arsitektur dalam Architecture Landscape yang Terkait dengan Arsitektur Bisnis'],
            ['id_kompetensi'=>18,'kode_kompetensi'=>'R18','kompetensi'=>'Memfinalisasikan Arsitektur Bisnis & Data'],
            ['id_kompetensi'=>19,'kode_kompetensi'=>'R19','kompetensi'=>'Menentukan Metode Pemodelan, Sudut Pandang dan Perangkat Bantu untuk Merancang Arsitektur Aplikasi'],
            ['id_kompetensi'=>20,'kode_kompetensi'=>'R20','kompetensi'=>'Menyusun Roadmap dan Komponen Arsitektur Aplikasi & Teknologi'],
            ['id_kompetensi'=>21,'kode_kompetensi'=>'R21','kompetensi'=>'Menentukan Metode Pemodelan Arsitektur Teknologi dan Technology Building Block yang Diperlukan'],
            ['id_kompetensi'=>22,'kode_kompetensi'=>'R22','kompetensi'=>'Memfinalisasikan Arsitektur Teknologi'],
            ['id_kompetensi'=>23,'kode_kompetensi'=>'R23','kompetensi'=>'Mengelola Ruang Lingkup Proyek'],
            ['id_kompetensi'=>24,'kode_kompetensi'=>'R24','kompetensi'=>'Mengelola Jadwal Waktu Proyek'],
            ['id_kompetensi'=>25,'kode_kompetensi'=>'R25','kompetensi'=>'Mengelola Komunikasi Proyek'],
            ['id_kompetensi'=>26,'kode_kompetensi'=>'R26','kompetensi'=>'Melakukan Identifikasi Sumber Kebutuhan'],
            ['id_kompetensi'=>27,'kode_kompetensi'=>'R27','kompetensi'=>'Menentukan Teknik Elisitasi yang Sesuai'],
            ['id_kompetensi'=>28,'kode_kompetensi'=>'R28','kompetensi'=>'Meninjau Ulang (Review) Kebutuhan Perangkat Lunak Melalui Spesifikasi dan Prototipe'],
            ['id_kompetensi'=>29,'kode_kompetensi'=>'R29','kompetensi'=>'Melakukan Validasi Model dan Uji Penerimaan Pengguna'],
            ['id_kompetensi'=>30,'kode_kompetensi'=>'R30','kompetensi'=>'Merancang Komponen Perangkat Lunak'],
            ['id_kompetensi'=>31,'kode_kompetensi'=>'R31','kompetensi'=>'Memberikan Pelayanan Produk-Produk Teknologi Informasi Sesuai Kebutuhan Bisnis'],
            ['id_kompetensi'=>32,'kode_kompetensi'=>'R32','kompetensi'=>'Mengelola Instalasi dan Pemeliharaan Sistem Perangkat Lunak'],
            ['id_kompetensi'=>33,'kode_kompetensi'=>'R33','kompetensi'=>'Mengelola Kemampuan dan Fungsionalitas Dari Seluruh Komponen TI'],
            ['id_kompetensi'=>34,'kode_kompetensi'=>'R34','kompetensi'=>'Menyusun Rencana Sprint'],
            ['id_kompetensi'=>35,'kode_kompetensi'=>'R35','kompetensi'=>'Menentukan Visi dan Tujuan Produk'],
            ['id_kompetensi'=>36,'kode_kompetensi'=>'R36','kompetensi'=>'Mengembangkan Backlog Produk'],
            ['id_kompetensi'=>37,'kode_kompetensi'=>'R37','kompetensi'=>'Memantau Kemajuan Pengembangan Produk'],
            ['id_kompetensi'=>38,'kode_kompetensi'=>'R38','kompetensi'=>'Memahami Prinsip-Prinsip Scrum'],
            ['id_kompetensi'=>39,'kode_kompetensi'=>'R39','kompetensi'=>'Memimpin dan Memfasilitasi Tim Scrum'],
            ['id_kompetensi'=>40,'kode_kompetensi'=>'R40','kompetensi'=>'Mengelola Proses Scrum'],
            ['id_kompetensi'=>41,'kode_kompetensi'=>'R41','kompetensi'=>'Mengukur dan Meningkatkan Kinerja Tim Scrum'],
            ['id_kompetensi'=>42,'kode_kompetensi'=>'R42','kompetensi'=>'Berkolaborasi dengan Berbagai Pemangku Kepentingan'],
            ['id_kompetensi'=>43,'kode_kompetensi'=>'R43','kompetensi'=>'Kemampuan komunikasi yang baik menjelaskan Backlog Produk'],
            ['id_kompetensi'=>44,'kode_kompetensi'=>'R44','kompetensi'=>'Menentukan Strategi Pelindungan Data Pribadi'],
            ['id_kompetensi'=>45,'kode_kompetensi'=>'R45','kompetensi'=>'Menerapkan Program Kerja Pelindungan Data Pribadi'],
            ['id_kompetensi'=>46,'kode_kompetensi'=>'R46','kompetensi'=>'Menyusun kebutuhan proses bisnis yang berjalan'],
            ['id_kompetensi'=>47,'kode_kompetensi'=>'R47','kompetensi'=>'Menyusun kriteria dan ukuran proses bisnis yang sesuai kebutuhan'],
            ['id_kompetensi'=>48,'kode_kompetensi'=>'R48','kompetensi'=>'Mengevaluasi hasil analisis gap'],
            ['id_kompetensi'=>49,'kode_kompetensi'=>'R49','kompetensi'=>'Menentukan kriteria sistem ERP'],
            ['id_kompetensi'=>50,'kode_kompetensi'=>'R50','kompetensi'=>'Mengidentifikasi kebutuhan transaksi operasional'],
            ['id_kompetensi'=>51,'kode_kompetensi'=>'R51','kompetensi'=>'Menentukan sistem ERP berdasarkan kebutuhan transaksi operasional'],
            ['id_kompetensi'=>52,'kode_kompetensi'=>'R52','kompetensi'=>'Menganalisis alternate flow dari proses bisnis'],
            ['id_kompetensi'=>53,'kode_kompetensi'=>'R53','kompetensi'=>'Melakukan pengujian sistem ERP sesuai kebutuhan pengguna (User Acceptance Test/UAT)'],
            ['id_kompetensi'=>54,'kode_kompetensi'=>'R54','kompetensi'=>'Menghasilkan proses bisnis yang sesuai dengan kebutuhan'],
            ['id_kompetensi'=>55,'kode_kompetensi'=>'R55','kompetensi'=>'Menyusun proses bisnis yang sesuai kebutuhan dalam bentuk dokumen'],
            ['id_kompetensi'=>56,'kode_kompetensi'=>'R56','kompetensi'=>'Membandingkan proses bisnis yang berjalan dengan proses bisnis yang sesuai kebutuhan'],
            ['id_kompetensi'=>57,'kode_kompetensi'=>'R57','kompetensi'=>'Membuat dokumen rencana perpindahan sistem'],
            ['id_kompetensi'=>58,'kode_kompetensi'=>'R58','kompetensi'=>'Mengevaluasi kriteria sistem ERP yang sesuai kebutuhan'],
            ['id_kompetensi'=>59,'kode_kompetensi'=>'R59','kompetensi'=>'Menyusun dokumen pengujian (test case)'],
            ['id_kompetensi'=>60,'kode_kompetensi'=>'R60','kompetensi'=>'Merancang rencana pemulihan dari bencana (disaster recovery plan)'],
            ['id_kompetensi'=>61,'kode_kompetensi'=>'R61','kompetensi'=>'Menerapkan Perlindungan Hak Kekayaan Intelektual'],
            ['id_kompetensi'=>62,'kode_kompetensi'=>'R62','kompetensi'=>'Menerapkan Kepemimpinan dan Komunikasi'],
            ['id_kompetensi'=>63,'kode_kompetensi'=>'R63','kompetensi'=>'Mengelola Proyek Secara Terintegrasi (Project Integration Management)'],
            ['id_kompetensi'=>64,'kode_kompetensi'=>'R64','kompetensi'=>'Mengelola Biaya Proyek (Project Cost Management)'],
            ['id_kompetensi'=>65,'kode_kompetensi'=>'R65','kompetensi'=>'Mengelola Kualitas Proyek (Project Quality Management)'],
            ['id_kompetensi'=>66,'kode_kompetensi'=>'R66','kompetensi'=>'Merencanakan dan mengorganisasi tim teknikal/teknologi'],
            ['id_kompetensi'=>67,'kode_kompetensi'=>'R67','kompetensi'=>'Merencanakan dan membuat teknologi yang disepakati'],
            ['id_kompetensi'=>68,'kode_kompetensi'=>'R68','kompetensi'=>'Melakukan penjadwalan (scheduling) konten/ program'],
            ['id_kompetensi'=>69,'kode_kompetensi'=>'R69','kompetensi'=>'Mengelola proses pembuatan asset teknologi'],
            ['id_kompetensi'=>70,'kode_kompetensi'=>'R70','kompetensi'=>'Mengumpulkan & Menelaah Data'],
            ['id_kompetensi'=>71,'kode_kompetensi'=>'R71','kompetensi'=>'Memvalidasi Data'],
            ['id_kompetensi'=>72,'kode_kompetensi'=>'R72','kompetensi'=>'Mengelola Kualitas Data'],
            ['id_kompetensi'=>73,'kode_kompetensi'=>'R73','kompetensi'=>'Mengelola Dokumen dan Konten'],
            ['id_kompetensi'=>74,'kode_kompetensi'=>'R74','kompetensi'=>'Menganalisis skalabilitas perangkat lunak'],
            ['id_kompetensi'=>75,'kode_kompetensi'=>'R75','kompetensi'=>'Melakukan identifikasi library, komponen atau framework yang diperlukan'],
            ['id_kompetensi'=>76,'kode_kompetensi'=>'R76','kompetensi'=>'Merancang arsitektur aplikasi'],
            ['id_kompetensi'=>77,'kode_kompetensi'=>'R77','kompetensi'=>'Mengimplementasikan network programming'],
            ['id_kompetensi'=>78,'kode_kompetensi'=>'R78','kompetensi'=>'Menerapkan pemrograman real time'],
            ['id_kompetensi'=>79,'kode_kompetensi'=>'R79','kompetensi'=>'Menerapkan pemrograman parallel'],
            ['id_kompetensi'=>80,'kode_kompetensi'=>'R80','kompetensi'=>'Menerapkan code review'],
            ['id_kompetensi'=>81,'kode_kompetensi'=>'R81','kompetensi'=>'Melaksanakan pengujian kode program secara statis'],
            ['id_kompetensi'=>82,'kode_kompetensi'=>'R82','kompetensi'=>'Melakukan pemantauan resource yang digunakan aplikasi'],
            ['id_kompetensi'=>83,'kode_kompetensi'=>'R83','kompetensi'=>'Merancang Struktur Perangkat Lunak'],
            ['id_kompetensi'=>84,'kode_kompetensi'=>'R84','kompetensi'=>'Merancang User Interface (UI) & User Experience (UX)'],
            ['id_kompetensi'=>85,'kode_kompetensi'=>'R85','kompetensi'=>'Melakukan Inventarisasi Software dan Hardware'],
            ['id_kompetensi'=>86,'kode_kompetensi'=>'R86','kompetensi'=>'Menerapkan standar standar keamanan informasi yang berlaku'],
            ['id_kompetensi'=>87,'kode_kompetensi'=>'R87','kompetensi'=>'Mengelola risiko keamanan informasi'],
            ['id_kompetensi'=>88,'kode_kompetensi'=>'R88','kompetensi'=>'Merumuskan kebutuhan pengguna'],
            ['id_kompetensi'=>89,'kode_kompetensi'=>'R89','kompetensi'=>'Merancang spesifikasi sesuai dengan fungsi dan kebutuhan pengguna'],
            ['id_kompetensi'=>90,'kode_kompetensi'=>'R90','kompetensi'=>'Memasang interface card'],
            ['id_kompetensi'=>91,'kode_kompetensi'=>'R91','kompetensi'=>'Memasang hard disk'],
            ['id_kompetensi'=>92,'kode_kompetensi'=>'R92','kompetensi'=>'Memasang motherboard'],
            ['id_kompetensi'=>93,'kode_kompetensi'=>'R93','kompetensi'=>'Memasang memory'],
            ['id_kompetensi'=>94,'kode_kompetensi'=>'R94','kompetensi'=>'Memasang prosesor'],
            ['id_kompetensi'=>95,'kode_kompetensi'=>'R95','kompetensi'=>'Memasang & Memperbaiki optical drive'],
            ['id_kompetensi'=>96,'kode_kompetensi'=>'R96','kompetensi'=>'Merawat dan Memperbaiki CPU'],
            ['id_kompetensi'=>97,'kode_kompetensi'=>'R97','kompetensi'=>'Merawat hard disk'],
            ['id_kompetensi'=>98,'kode_kompetensi'=>'R98','kompetensi'=>'Merawat peripheral'],
            ['id_kompetensi'=>99,'kode_kompetensi'=>'R99','kompetensi'=>'Memperbaiki keyboard'],
            ['id_kompetensi'=>100,'kode_kompetensi'=>'R100','kompetensi'=>'Memperbaiki monitor'],
            ['id_kompetensi'=>101,'kode_kompetensi'=>'R101','kompetensi'=>'Memperbaiki printer'],
            ['id_kompetensi'=>102,'kode_kompetensi'=>'R102','kompetensi'=>'Memperbaiki scanner'],
            ['id_kompetensi'=>103,'kode_kompetensi'=>'R103','kompetensi'=>'Memperbaiki proyektor'],
            ['id_kompetensi'=>104,'kode_kompetensi'=>'R104','kompetensi'=>'Melakukan setting BIOS'],
            ['id_kompetensi'=>105,'kode_kompetensi'=>'R105','kompetensi'=>'Melakukan instalasi sistem operasi'],
            ['id_kompetensi'=>106,'kode_kompetensi'=>'R106','kompetensi'=>'Melakukan instalasi software aplikasi'],
            ['id_kompetensi'=>107,'kode_kompetensi'=>'R107','kompetensi'=>'Melakukan negosiasi kebutuhan perangkat lunak'],
            ['id_kompetensi'=>108,'kode_kompetensi'=>'R108','kompetensi'=>'Menyusun kebutuhan dokumentasi spesifikasi perangkat lunak'],
            ['id_kompetensi'=>109,'kode_kompetensi'=>'R109','kompetensi'=>'Menyusun spesifikasi kebutuhan sistem & perangkat lunak'],
            ['id_kompetensi'=>110,'kode_kompetensi'=>'R110','kompetensi'=>'Mengimplementasikan kebutuhan organisasi pada layanan cloud'],
            ['id_kompetensi'=>111,'kode_kompetensi'=>'R111','kompetensi'=>'Mengklasifikasikan informasi yang bersifat rahasia'],
            ['id_kompetensi'=>112,'kode_kompetensi'=>'R112','kompetensi'=>'Melaksanakan pengamanan informasi yang bersifat rahasia'],
            ['id_kompetensi'=>113,'kode_kompetensi'=>'R113','kompetensi'=>'Merancang Mobile Security Measurement'],
            ['id_kompetensi'=>114,'kode_kompetensi'=>'R114','kompetensi'=>'Mengembangkan Smart Client Security'],
            ['id_kompetensi'=>115,'kode_kompetensi'=>'R115','kompetensi'=>'Merancang Tentang Wireless Security Protocol'],
            ['id_kompetensi'=>116,'kode_kompetensi'=>'R116','kompetensi'=>'Melaksanakan Mobile Forensic'],
            ['id_kompetensi'=>117,'kode_kompetensi'=>'R117','kompetensi'=>'Membuat Mobile Unified Communication'],
            ['id_kompetensi'=>118,'kode_kompetensi'=>'R118','kompetensi'=>'Mengembangkan Mobile Financial'],
            ['id_kompetensi'=>119,'kode_kompetensi'=>'R119','kompetensi'=>'Merancang Mobile Cloud Computing'],
            ['id_kompetensi'=>120,'kode_kompetensi'=>'R120','kompetensi'=>'Merancang Spesifikasi Teknis Smart Phone/Tablet Sesuai Kebutuhan Pengguna'],
            ['id_kompetensi'=>121,'kode_kompetensi'=>'R121','kompetensi'=>'Merancang Wireless Sensor Network (WSN)'],
            ['id_kompetensi'=>122,'kode_kompetensi'=>'R122','kompetensi'=>'Menunjukkan Internet of Things (IoT) Dan Smart City Technology'],
            ['id_kompetensi'=>123,'kode_kompetensi'=>'R123','kompetensi'=>'Menggunakan Spesifikasi Program'],
            ['id_kompetensi'=>124,'kode_kompetensi'=>'R124','kompetensi'=>'Menulis Kode dengan Prinsip Sesuai Guidelines dan Best Practices'],
            ['id_kompetensi'=>125,'kode_kompetensi'=>'R125','kompetensi'=>'Mengimplementasikan Pemrograman Berorientasi Objek'],
            ['id_kompetensi'=>126,'kode_kompetensi'=>'R126','kompetensi'=>'Menggunakan Library atau Komponen Pre-Existing'],
            ['id_kompetensi'=>127,'kode_kompetensi'=>'R127','kompetensi'=>'Menerapkan Akses Basis Data'],
            ['id_kompetensi'=>128,'kode_kompetensi'=>'R128','kompetensi'=>'Membuat Dokumen Kode Program'],
            ['id_kompetensi'=>129,'kode_kompetensi'=>'R129','kompetensi'=>'Melakukan Debugging'],
            ['id_kompetensi'=>130,'kode_kompetensi'=>'R130','kompetensi'=>'Melaksanakan Pengujian Unit Program'],
            ['id_kompetensi'=>131,'kode_kompetensi'=>'R131','kompetensi'=>'Membuat Mobile Digital Media'],
            ['id_kompetensi'=>132,'kode_kompetensi'=>'R132','kompetensi'=>'Memberikan Petunjuk Teknis Kepada Pelanggan'],
            ['id_kompetensi'=>133,'kode_kompetensi'=>'R133','kompetensi'=>'Menerapkan Perintah Eksekusi Bahasa Pemrograman Berbasis Teks, Grafik, dan Multimedia'],
            ['id_kompetensi'=>134,'kode_kompetensi'=>'R134','kompetensi'=>'Mengaplikasikan Metodologi Pengembangan Perangkat Lunak'],
            ['id_kompetensi'=>135,'kode_kompetensi'=>'R135','kompetensi'=>'Menentukan Framework'],
            ['id_kompetensi'=>136,'kode_kompetensi'=>'R136','kompetensi'=>'Menentukan Lingkup Quality Assurance untuk Perangkat Lunak'],
            ['id_kompetensi'=>137,'kode_kompetensi'=>'R137','kompetensi'=>'Menentukan Lingkup Quality Assurance untuk Proses Pengembangan Perangkat Lunak'],
            ['id_kompetensi'=>138,'kode_kompetensi'=>'R138','kompetensi'=>'Mengelola Risiko Penjaminan Kualitas'],
            ['id_kompetensi'=>139,'kode_kompetensi'=>'R139','kompetensi'=>'Mendefinisikan Sumber Daya yang Dibutuhkan'],
            ['id_kompetensi'=>140,'kode_kompetensi'=>'R140','kompetensi'=>'Mengintegrasikan Penjaminan Kualitas ke Dalam Organisasi Pengembang'],
            ['id_kompetensi'=>141,'kode_kompetensi'=>'R141','kompetensi'=>'Memverifikasi Pelaksanaan Tahapan Pengembangan Perangkat Lunak'],
            ['id_kompetensi'=>142,'kode_kompetensi'=>'R142','kompetensi'=>'Determine and Confirm Client Business Requirements'],
            ['id_kompetensi'=>143,'kode_kompetensi'=>'R143','kompetensi'=>'Develop Macros and Templates for Clients Using Standard Products'],
            ['id_kompetensi'=>144,'kode_kompetensi'=>'R144','kompetensi'=>'Plan Process Re-Engineering Strategies for Business'],
            ['id_kompetensi'=>145,'kode_kompetensi'=>'R145','kompetensi'=>'Facilitate Business Analysis'],
            ['id_kompetensi'=>146,'kode_kompetensi'=>'R146','kompetensi'=>'Model Data Processes'],
            ['id_kompetensi'=>147,'kode_kompetensi'=>'R147','kompetensi'=>'Analyse Stakeholder Requirements'],
            ['id_kompetensi'=>148,'kode_kompetensi'=>'R148','kompetensi'=>'Select New Technology Models for Business'],
            ['id_kompetensi'=>149,'kode_kompetensi'=>'R149','kompetensi'=>'Gather Data to Identify Business Requirements'],
            ['id_kompetensi'=>150,'kode_kompetensi'=>'R150','kompetensi'=>'Determine Appropriate IT Strategies and Solutions'],
            ['id_kompetensi'=>151,'kode_kompetensi'=>'R151','kompetensi'=>'Match IT Needs With The Strategic Direction of The Enterprise'],
            ['id_kompetensi'=>152,'kode_kompetensi'=>'R152','kompetensi'=>'Verify Client Business Requirements'],
            ['id_kompetensi'=>153,'kode_kompetensi'=>'R153','kompetensi'=>'Develop Workplace Policy and Procedures for Sustainability'],
            ['id_kompetensi'=>154,'kode_kompetensi'=>'R154','kompetensi'=>'Ensure Team Effectiveness'],
            ['id_kompetensi'=>155,'kode_kompetensi'=>'R155','kompetensi'=>'Review Developed Software'],
            ['id_kompetensi'=>156,'kode_kompetensi'=>'R156','kompetensi'=>'Validate an Application Design Against Specifications'],
            ['id_kompetensi'=>157,'kode_kompetensi'=>'R157','kompetensi'=>'Develop Detailed Test Plans'],
            ['id_kompetensi'=>158,'kode_kompetensi'=>'R158','kompetensi'=>'Manage The Testing Process'],
            ['id_kompetensi'=>159,'kode_kompetensi'=>'R159','kompetensi'=>'Membuat Perencanaan Pengujian Detail (Detailed Test Plan)'],
            ['id_kompetensi'=>160,'kode_kompetensi'=>'R160','kompetensi'=>'Melaksanakan Cutover Aplikasi'],
            ['id_kompetensi'=>161,'kode_kompetensi'=>'R161','kompetensi'=>'Melaksanakan Pengujian Oleh Pengguna (UAT)'],
            ['id_kompetensi'=>162,'kode_kompetensi'=>'R162','kompetensi'=>'Menggunakan SQL'],
            ['id_kompetensi'=>163,'kode_kompetensi'=>'R163','kompetensi'=>'Menerapkan Alert Notification Jika Aplikasi Bermasalah'],
            ['id_kompetensi'=>164,'kode_kompetensi'=>'R164','kompetensi'=>'Melakukan Migrasi ke Teknologi Baru'],
            ['id_kompetensi'=>165,'kode_kompetensi'=>'R165','kompetensi'=>'Melakukan Pembaharuan Perangkat Lunak'],
            ['id_kompetensi'=>166,'kode_kompetensi'=>'R166','kompetensi'=>'Menerapkan Pemrograman Multimedia'],
            ['id_kompetensi'=>167,'kode_kompetensi'=>'R167','kompetensi'=>'Menentukan Arsitektur Perangkat Keras'],
            ['id_kompetensi'=>168,'kode_kompetensi'=>'R168','kompetensi'=>'Menganalisis Tools'],
            ['id_kompetensi'=>169,'kode_kompetensi'=>'R169','kompetensi'=>'Menganalisis Dampak Perubahan Terhadap Aplikasi'],
            ['id_kompetensi'=>170,'kode_kompetensi'=>'R170','kompetensi'=>'Mengimplementasikan Algoritma Pemrograman'],
            ['id_kompetensi'=>171,'kode_kompetensi'=>'R171','kompetensi'=>'Menggunakan Struktur Data'],
            ['id_kompetensi'=>172,'kode_kompetensi'=>'R172','kompetensi'=>'Mengimplementasikan Rancangan Entitas dan Keterkaitan antar Entitas'],
            ['id_kompetensi'=>173,'kode_kompetensi'=>'R173','kompetensi'=>'Melaksanakan Konfigurasi Perangkat Lunak Sesuai Environment (Development, Staging, Production)'],
            ['id_kompetensi'=>174,'kode_kompetensi'=>'R174','kompetensi'=>'Melakukan Profiling Program'],
            ['id_kompetensi'=>175,'kode_kompetensi'=>'R175','kompetensi'=>'Menentukan Arsitektur Perangkat Lunak'],
        ]);
    }
}